/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: EmilyHortonIntroDraft.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @EmilyHortonIntroDraft: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
			VarDef("playerName", () => this.@playerName, val => this.@playerName = val);
			VarDef("brosonnaName", () => this.@brosonnaName, val => this.@brosonnaName = val);
			VarDef("availability", () => this.@availability, val => this.@availability = val);
			VarDef("commonality", () => this.@commonality, val => this.@commonality = val);
			VarDef("familiarity", () => this.@familiarity, val => this.@familiarity = val);
			VarDef("friendliness", () => this.@friendliness, val => this.@friendliness = val);
			VarDef("flirtiness", () => this.@flirtiness, val => this.@flirtiness = val);
			VarDef("intelligence", () => this.@intelligence, val => this.@intelligence = val);
		}

		public StoryVar @playerName;
		public StoryVar @brosonnaName;
		public StoryVar @availability;
		public StoryVar @commonality;
		public StoryVar @familiarity;
		public StoryVar @friendliness;
		public StoryVar @flirtiness;
		public StoryVar @intelligence;
	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@EmilyHortonIntroDraft()
	{
		this.StartPassage = "Setup";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
		passage15_Init();
		passage16_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Setup

	void passage1_Init()
	{
		this.Passages[@"Setup"] = new StoryPassage(@"Setup", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Variables are getting set here.");
		yield return lineBreak();
		yield return text("Twine seems incapable of setting variables without putting a ton of whitespace in the passage.");
		yield return lineBreak();
		Vars.playerName  = "Sammy";
		yield return lineBreak();
		Vars.brosonnaName  = "Josh";
		yield return lineBreak();
		yield return lineBreak();
		Vars.availability  = 0;
		yield return lineBreak();
		Vars.commonality  = 0;
		yield return lineBreak();
		Vars.familiarity  = 2;
		yield return lineBreak();
		Vars.friendliness  = 2;
		yield return lineBreak();
		Vars.flirtiness  = 0;
		yield return lineBreak();
		Vars.intelligence  = 0;
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Start", "Start", null);
		yield break;
	}


	// .............
	// #2: That Guy

	void passage2_Init()
	{
		this.Passages[@"That Guy"] = new StoryPassage(@"That Guy", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("\"Hey ");
		yield return text(Vars.playerName);
		yield return text(", it's nice to see you again!\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Hm. Who was this guy again? You definitely recognize him from one of your classes last year, but you only talked very briefly at the end of the last semster.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Hey... you!\"", "Catching Up", null);
		yield return lineBreak();
		yield return link("\"Don't be mad, but uh, what was your name again?\"", "Reintroduction", null);
		yield break;
	}


	// .............
	// #3: Start

	void passage3_Init()
	{
		this.Passages[@"Start"] = new StoryPassage(@"Start", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("It is a bright and early August Monday. You have just arrived to your first class of sophomore year. Outside, a variety of familiar students linger around waiting for the professor to arrive. Who would you like to talk to?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("That Guy", "That Guy", null);
		yield break;
	}


	// .............
	// #4: Reintroduction

	void passage4_Init()
	{
		this.Passages[@"Reintroduction"] = new StoryPassage(@"Reintroduction", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("\"Ah, I guess it was a while ago...\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("He seems dissapointed for a moment, but seems to recover fairly quickly. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"My name is ");
		yield return text(Vars.brosonnaName);
		yield return text(". We had GDAPS 1 together. I didn't talk much in class, but I posted memes pretty frequently in the class Discord.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Right, I remember now!\"", "Catching Up", null);
		yield return lineBreak();
		Vars.familiarity  = Vars.familiarity - 1;
		yield break;
	}


	// .............
	// #5: Catching Up

	void passage5_Init()
	{
		this.Passages[@"Catching Up"] = new StoryPassage(@"Catching Up", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		if(Vars.familiarity > 2) {
			yield return text("He smiles widely. \"It's so good to see you again!\"");
		}
		yield return lineBreak();
		yield return lineBreak();
		using (Group("em", true)) {
			yield return text("I wonder how he remembers my name...");
		}
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"Word on the street is that this class is pretty tough.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Yeah, especially if you're a girl.\"", "Sexist Professor?", null);
		yield return lineBreak();
		yield return link("(Nod)", "Pretty Tough", null);
		yield return lineBreak();
		using (Group("hook", "h00001"))
			yield return link("Maybe, but I'm up for the challenge!", null, () => enchantHook("h00001", HarloweEnchantCommand.Replace, passage5_Fragment_0));
		yield break;
	}

	IStoryThread passage5_Fragment_0()
	{
		yield return lineBreak();
		yield return text("	");
		Vars.friendliness  = Vars.friendliness + 1;
		yield return lineBreak();
		yield return text("	");
		Vars.commonality  = Vars.commonality + 1;
		yield return lineBreak();
		yield return text("	");
		yield return abort(goToPassage: "Pretty Tough");
		yield return lineBreak();
		yield break;
	}

	// .............
	// #6: Pretty Tough

	void passage6_Init()
	{
		this.Passages[@"Pretty Tough"] = new StoryPassage(@"Pretty Tough", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		if(Vars.commonality >= 1) {
			yield return text("\"Oh yeah, I totally feel the same way!\"");
		}
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"Coding is my thing though. Whatever happens after college, I'll be happy as a long as I'm coding, you know? They always say it's tough to get into the game industry, even with a degree. If you need any help for this class, I'm always avaialable to help!\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Really? Always?\"", "\"Really? Always?\"", null);
		yield return lineBreak();
		yield return link("\"I'm sure I can handle it myself.", "Handle Myself", null);
		yield return lineBreak();
		yield return link("\"Plus, you don't have to deal with a sexist professor.\"", "Sexist Professor?", null);
		yield break;
	}


	// .............
	// #7: Sexist Professor?

	void passage7_Init()
	{
		this.Passages[@"Sexist Professor?"] = new StoryPassage(@"Sexist Professor?", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text(Vars.brosonnaName);
		yield return text(" tilts his head in confusion.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"What do you mean? I know some people around the school sometimes think less of girls because they are sexist morons, but it's definitely not true! But... are you saying this professor is sexist?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"That is exactly what I am saying.\"", "Doubt", null);
		yield return lineBreak();
		yield return link("\"After enough complaints, there was an investigation...\"", "Investigation", null);
		yield break;
	}


	// .............
	// #8: Doubt

	void passage8_Init()
	{
		this.Passages[@"Doubt"] = new StoryPassage(@"Doubt", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("\"A professor being sexist? I guess it's not impossible, but wouldn't it be obvious? I mean, sexism isn't exactly a common thing these days.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"After enough complaints, there was an investigation...\"", "Investigation", null);
		yield return lineBreak();
		yield return link("\"Trust me. It's still pretty common.\"", "Give Him a Chance", null);
		yield break;
	}


	// .............
	// #9: Investigation

	void passage9_Init()
	{
		this.Passages[@"Investigation"] = new StoryPassage(@"Investigation", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("You take a moment to explain the situation to ");
		yield return text(Vars.brosonnaName);
		yield return text(". The allegations piling up over years, the eventual investigation, and the conclusion that every girl who studied under him already knew- he was a sexist and treated women with bias.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Of course, firing professors isn't always easy, especially if they are well-respected by enough people in their field.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(Vars.brosonnaName);
		yield return text(" seems concerned, but somehow conflicted?");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"It's just really tough to believe. With how this school always pushes diversity, I would think this type of thing wouldn't stand. Maybe he's changed? Or maybe it was all a misunderstanding. Don't we all have that one aunt or uncle who has some bad views just because they are a product of their time, but otherwise they have a lot of great qualities to them?\"");
		yield return lineBreak();
		Vars.intelligence  = Vars.intelligence + 1;
		yield return lineBreak();
		yield return link("\"It's easy to ignore if you're not the victim.\"", "Give Him a Chance", null);
		yield break;
	}


	// .............
	// #10: Give Him a Chance

	void passage10_Init()
	{
		this.Passages[@"Give Him a Chance"] = new StoryPassage(@"Give Him a Chance", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text(Vars.brosonnaName);
		yield return text(" seems to have taken you a little seriously. At the very lest, he does seem to be genuinely thinking about the issue. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"Well, let's give him a chance. Maybe the investigation was enough to get him to change. But hey... I'll do whatever I can to support you if it becomes an issue!\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Thanks, I'll keep that in mind.\"", "End Scene (or next Bro?)", null);
		yield return lineBreak();
		yield return link("\"I'm sure I can handle it myself.", "Handle Myself", null);
		yield break;
	}


	// .............
	// #11: ""Really? Always?""

	void passage11_Init()
	{
		this.Passages[@"""Really? Always?"""] = new StoryPassage(@"""Really? Always?""", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return text(Vars.brosonnaName);
		yield return text(" laughs at your joke. A little too hard.");
		yield return lineBreak();
		Vars.friendliness  = Vars.friendliness + 1;
		yield return lineBreak();
		yield return text("\"Honestly, most nights I would probably still be reachable at three in the morning, if that's what you are suggesting. Besides...\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(Vars.brosonnaName);
		yield return text(" hesitates a moment before finally saying \"Honestly, I'd be delighted whenever you decided to message me.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"I'm sure I can handle it myself.", "Handle Myself", null);
		yield break;
	}


	// .............
	// #12: Handle Myself

	void passage12_Init()
	{
		this.Passages[@"Handle Myself"] = new StoryPassage(@"Handle Myself", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return text("\"Yes, of course! I didn't mean you weren't capable, I just wanted to be helpful is all... and maybe I just wanted to increase my chances of hearing from you.\"");
		yield return lineBreak();
		Vars.intelligence  = Vars.intelligence + 1;
		yield return lineBreak();
		yield return lineBreak();
		if(Vars.friendliness >= 4) {
			yield return text("After seeming to think on something, he continues. ");
			yield return lineBreak();
			yield return lineBreak();
			yield return text("\"I know we haven't really talked a whole ton, but you always seemed like an awesome girl. I hope we can get to know one another even more this semester.\"");
		}
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Um, yeah, maybe!\"", "\"Um, yeah, maybe!\"", null);
		yield return lineBreak();
		yield return link("\"That's... nice.\"", "\"That's... nice.\"", null);
		yield break;
	}


	// .............
	// #13: ""That's... nice.""

	void passage13_Init()
	{
		this.Passages[@"""That's... nice."""] = new StoryPassage(@"""That's... nice.""", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return text("\"Shoot. I didn't mean to make that awkward.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("(Shrug it off)", "End Scene (or next Bro?)", null);
		yield break;
	}


	// .............
	// #14: ""Um, yeah, maybe!""

	void passage14_Init()
	{
		this.Passages[@"""Um, yeah, maybe!"""] = new StoryPassage(@"""Um, yeah, maybe!""", new string[]{  }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		yield return text(Vars.brosonnaName);
		yield return text(" seems happy with your response, but just kind of awkwardly looks away, smiling.");
		yield return lineBreak();
		Vars.flirtiness  = Vars.flirtiness + 1;
		yield return lineBreak();
		using (Group("em", true)) {
			yield return text("Is he flirting?");
		}
		yield return lineBreak();
		yield return lineBreak();
		yield return link("(Awkwardly look away)", "End Scene (or next Bro?)", null);
		yield break;
	}


	// .............
	// #15: End Scene (or next Bro?)

	void passage15_Init()
	{
		this.Passages[@"End Scene (or next Bro?)"] = new StoryPassage(@"End Scene (or next Bro?)", new string[]{  }, passage15_Main);
	}

	IStoryThread passage15_Main()
	{
		yield return text("You notice that there is a commotion in the hall.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"Oh, hey, it looks like the professor is here! I guess we can talk more about this later!\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(Vars.brosonnaName);
		yield return text(" files into the class with the other students. Looks like it's time to see if the rumors about the class are true.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Debug/Notes", "Debug/Notes", null);
		yield break;
	}


	// .............
	// #16: Debug/Notes

	void passage16_Init()
	{
		this.Passages[@"Debug/Notes"] = new StoryPassage(@"Debug/Notes", new string[]{  }, passage16_Main);
	}

	IStoryThread passage16_Main()
	{
		yield return text("Normally, players do not get to see these stats. You must be a developer");
		yield return lineBreak();
		yield return text("or a play-tester. Awesome!");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return text("The brosonna has the following impression of you for each of these stats.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Availability: ");
		yield return text(Vars.availability);
		yield return lineBreak();
		yield return text("Commonality: ");
		yield return text(Vars.commonality);
		yield return lineBreak();
		yield return text("Familiarity: ");
		yield return text(Vars.familiarity);
		yield return lineBreak();
		yield return text("Friendliness: ");
		yield return text(Vars.friendliness);
		yield return lineBreak();
		yield return text("Flirtiness: ");
		yield return text(Vars.flirtiness);
		yield return lineBreak();
		yield return text("Intelligence: ");
		yield return text(Vars.intelligence);
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Availability: How easy the Bro thinks you are to reach- text, calls, hangouts, etc. Higher availability will mean... more texts, calls, hangouts, etc.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Commonality: How much the bro thinks you have in common with him. Higher commonality encourages more revealing/personal information shared with the player or asked of the player.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Familiarity: Simply a measurement of how well the Bro thinks you two know each other. Sort of similar to commonality. Might be merged, might not be.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Friendliness: This one is an interesting one. On one hand, it's similar to the previous two stats in that being friendlier should generally unlock more close-friend dialogue options. However, losing friendliness might also make the bro grow impatient, short-tempered, or callous. For this bro in particular, friendliness will be pretty hard to reduce- he is, after all, the unrelenting suitor who thinks you two have something when really, maybe, you don't. I think that this is an idea worth exploring/considering: How easily will the different stats increase/decrease for the different bros? Some guys might take offense to you standing up for yourself and immedietly think you're just being a bitch. Others might have the opposite effect and never stop trying to be friendly/flirty.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Flirtiness: Your Bro might get the idea that you are flirting with him. I envision flirtiness is sort of the \"danger\" stat. Higher levels of flirtiness could lead to more extreme romantic/physical gestures from bros. I don't think that the player will ever ");
		using (Group("em", true)) {
			yield return text("intentionally");
		}
		yield return text(" raise this stat, but certain friendly/polite actions will be taken as being flirtatious.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Idea to experiment with- not all of these stats start at 0. Maybe some brosonnas actually have the hidden goal of trying to reduce their base flirtiness perception to a point where they are less dangerous. Of course, the numbers are hidden, but it might be a way to reward/encourage players to pick the \"safer\" or \"defusing\" dialogue options.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Intelligence: This is another weird one, and intelligence might not be what I'm going for here. I'm thinking of definining it both in terms of how smart/competent your bro thinks you are, but also how much he respects you as an individual capable of being self-sufficient.");
		yield break;
	}


}