/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: SamIntroDraft.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @SamIntroDraft: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@SamIntroDraft()
	{
		this.StartPassage = "Start";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
		passage15_Init();
		passage16_Init();
		passage17_Init();
		passage18_Init();
		passage19_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Start

	void passage1_Init()
	{
		this.Passages[@"Start"] = new StoryPassage(@"Start", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("REDACTED notices you looking in his direction");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"Hey! Long time no see! How did summer treat ya?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"It was alright\"", "\"It was alright\"", null);
		yield return lineBreak();
		yield return link("\"It was awesome!\"", "\"It was awesome!\"", null);
		yield return lineBreak();
		yield return link("\"I just worked all summer\"", "\"I just worked all summer\"", null);
		yield break;
	}


	// .............
	// #2: ""It was alright""

	void passage2_Init()
	{
		this.Passages[@"""It was alright"""] = new StoryPassage(@"""It was alright""", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("\"Mine was wild. I started making this game engine from scratch because⁠— well, you know how much Unity sucks⁠— and I got multi-threading working. Did you make anything over the break?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"I made a twine game\"", "\"I made a twine game\"", null);
		yield return lineBreak();
		yield return link("\"No, I was too busy\"", "\"No, I was too busy\"", null);
		yield break;
	}


	// .............
	// #3: ""It was awesome!""

	void passage3_Init()
	{
		this.Passages[@"""It was awesome!"""] = new StoryPassage(@"""It was awesome!""", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("\"GOD I'm jealous. I worked at this dumb military contractor for ten weeks, and I swear nobody there knew what they were doing.\" ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Oh\"", "\"Oh\"", null);
		yield return lineBreak();
		yield return link("\"That sucks\"", "\"That sucks\"", null);
		yield return lineBreak();
		yield return link("\"You got a coding job, that's cool\"", "\"You got a coding job, that's cool\"", null);
		yield break;
	}


	// .............
	// #4: ""I just worked all summer""

	void passage4_Init()
	{
		this.Passages[@"""I just worked all summer"""] = new StoryPassage(@"""I just worked all summer""", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("\"SAME! It was at this dumb company that didn't even know the difference between C and C++.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Oh\"", "\"Oh\"", null);
		yield return lineBreak();
		yield return link("\"That sucks\"", "\"That sucks\"", null);
		yield return lineBreak();
		yield return link("\"You got a coding job, that's cool\"", "\"You got a coding job, that's cool\"", null);
		yield break;
	}


	// .............
	// #5: ""Oh""

	void passage5_Init()
	{
		this.Passages[@"""Oh"""] = new StoryPassage(@"""Oh""", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("Just then, the professor arrives, and the students in the hall start filing into the room slowly.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"I'm so excited to have another class with Professor REDACTED. Let's sit up front with him, come on.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("He pushes through the crowd in an attempt to lead you to the front of the room.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Follow him", "Follow him", null);
		yield return lineBreak();
		yield return link("Hang back", "Hang back", null);
		yield break;
	}


	// .............
	// #6: ""That sucks""

	void passage6_Init()
	{
		this.Passages[@"""That sucks"""] = new StoryPassage(@"""That sucks""", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("\"Yeah, it was the worst. An art major could have done the work they assigned me.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Oh\"", "\"Oh\"", null);
		yield break;
	}


	// .............
	// #7: ""You got a coding job, that's cool""

	void passage7_Init()
	{
		this.Passages[@"""You got a coding job, that's cool"""] = new StoryPassage(@"""You got a coding job, that's cool""", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("\"No no no. Video games are cool. Dragons are cool. Being the only computer-literate intern at a tech company is not cool.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Oh\"", "\"Oh\"", null);
		yield break;
	}


	// .............
	// #8: ""I made a twine game""

	void passage8_Init()
	{
		this.Passages[@"""I made a twine game"""] = new StoryPassage(@"""I made a twine game""", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("\"No I mean like a ");
		using (Group("italic", true)) {
			yield return text("real");
		}
		yield return text(" game.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Um...\"", "\"Um...\"", null);
		yield return lineBreak();
		yield return link("\"I guess not then\"", "\"I guess not then\"", null);
		yield break;
	}


	// .............
	// #9: ""No, I was too busy""

	void passage9_Init()
	{
		this.Passages[@"""No, I was too busy"""] = new StoryPassage(@"""No, I was too busy""", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("\"I mean I was busy too, ");
		using (Group("italic", true)) {
			yield return text("technically");
		}
		yield return text(". I would get my work done at the office so fast that I just spent most of my time there picking at my engine.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"That wasn't really an option for me\"", "\"That wasn't really an option for me\"", null);
		yield return lineBreak();
		yield return link("\"You got a coding job, that's cool\"", "\"You got a coding job, that's cool\"", null);
		yield break;
	}


	// .............
	// #10: ""That wasn't really an option for me""

	void passage10_Init()
	{
		this.Passages[@"""That wasn't really an option for me"""] = new StoryPassage(@"""That wasn't really an option for me""", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text("\"Sorry. Sometimes I forget that people have responsibilities that don't involve a monitor and keyboard.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Um...\"", "\"Um...\"", null);
		yield break;
	}


	// .............
	// #11: ""Um...""

	void passage11_Init()
	{
		this.Passages[@"""Um..."""] = new StoryPassage(@"""Um...""", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return text("Just then, the professor arrives, and the students in the hall start filing into the room slowly.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"Hey, we should sit together. I like to sit in the front of the room, so I can bother the professor.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Follow him", "Follow him", null);
		yield return lineBreak();
		yield return link("Hang back", "Hang back", null);
		yield break;
	}


	// .............
	// #12: ""I guess not then""

	void passage12_Init()
	{
		this.Passages[@"""I guess not then"""] = new StoryPassage(@"""I guess not then""", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return text("\"Well it's no problem. I could probably show you how to make a game in my engine if you like. It's super easy, as long as you're good with C.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("\"Um...\"", "\"Um...\"", null);
		yield break;
	}


	// .............
	// #13: Follow him

	void passage13_Init()
	{
		this.Passages[@"Follow him"] = new StoryPassage(@"Follow him", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return text("You and REDACTED sit side-by-side at the front of the room, across from the professor's seat. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"Professor, look! I've got a new friend\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("REDACTED spends the few minutes before class starts by loudly repeating what he told you in the hall to the professor.");
		yield break;
	}


	// .............
	// #14: Hang back

	void passage14_Init()
	{
		this.Passages[@"Hang back"] = new StoryPassage(@"Hang back", new string[]{  }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		yield return text("REDACTED saves a seat for you in the front of the room with his backpack and motions for you to come to him");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Try to signal a \"no thanks, I'm good\"", "Try to signal a \"no thanks, I'm good\"", null);
		yield return lineBreak();
		yield return link("Go to him", "Go to him", null);
		yield return lineBreak();
		yield return link("Ignore", "Ignore", null);
		yield break;
	}


	// .............
	// #15: Try to signal a ""no thanks, I'm good""

	void passage15_Init()
	{
		this.Passages[@"Try to signal a ""no thanks, I'm good"""] = new StoryPassage(@"Try to signal a ""no thanks, I'm good""", new string[]{  }, passage15_Main);
	}

	IStoryThread passage15_Main()
	{
		yield return text("He makes an exaggerated frowny face and takes his backpack off the seat.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Class begins a few minutes later.");
		yield break;
	}


	// .............
	// #16: Go to him

	void passage16_Init()
	{
		this.Passages[@"Go to him"] = new StoryPassage(@"Go to him", new string[]{  }, passage16_Main);
	}

	IStoryThread passage16_Main()
	{
		yield return text("\"I thought for a second that you abandoned me. In any case, it's good to have you back!\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("He gives you a big pat on the shoulder.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("REDACTED spends the few minutes before class starts by loudly repeating what he told you in the hall to the professor.");
		yield break;
	}


	// .............
	// #17: Ignore

	void passage17_Init()
	{
		this.Passages[@"Ignore"] = new StoryPassage(@"Ignore", new string[]{  }, passage17_Main);
	}

	IStoryThread passage17_Main()
	{
		yield return text("After a moment, he moves on to frantically waving in your direction with an exaggerated smile on his face.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Smile and wave back", "Smile and wave back", null);
		yield return lineBreak();
		yield return link("Continue to ignore", "Continue to ignore", null);
		yield return lineBreak();
		yield return link("Go to him", "Go to him", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #18: Smile and wave back

	void passage18_Init()
	{
		this.Passages[@"Smile and wave back"] = new StoryPassage(@"Smile and wave back", new string[]{  }, passage18_Main);
	}

	IStoryThread passage18_Main()
	{
		yield return text("He starts signalling for you to take the seat next to him again.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Try to signal a \"no thanks, I'm good\"", "Try to signal a \"no thanks, I'm good\"", null);
		yield return lineBreak();
		yield return link("Go to him", "Go to him", null);
		yield break;
	}


	// .............
	// #19: Continue to ignore

	void passage19_Init()
	{
		this.Passages[@"Continue to ignore"] = new StoryPassage(@"Continue to ignore", new string[]{  }, passage19_Main);
	}

	IStoryThread passage19_Main()
	{
		yield return text("You hear redacted talking to the professor loudly from across the room.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Class begins a few minutes later.");
		yield break;
	}


}